# Site settings
title: The Great Netlify Experiment
email: renny.carney@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm Irenka Carney, and this site is an experiment! ... Specifically a litmus test of my abilities in the context of Netlify support work. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://www.cartographer-firings-30846.netlify.com # the base hostname & protocol for your site
twitter_username: wrentaur
github_username:  wrentaur


# Build settings
markdown: kramdown
